project:
  type: website
  output-dir: docs
  render:
    - /*.qmd
    - Quarto/*/*.qmd 
    - Quarto/*.qmd

website:
  title: "Benefits Estimator"
  page-navigation: true
  sidebar:
    contents: auto
  navbar:
    left:
      - href: index.qmd
        text: Home
  
format: 
  html:
    html-math-method: mathjax
    fig-responsive: true
    toc: true
    toc-location: left
    theme: cosmo
    page-layout: full
execute: 
  cache: true
  python-path: src

editor:
    render-on-save: true
bibliography: /home/fitsl/library/zotero/fjk_library.bib