---
title: Benefits Estimator Overview and Roadmap
author: Fitz Koch
date: today
description:  Summary of the project and a roadmap of what will be included in it.
---

Generally, this is intended as an interactive modernization of 
[this presentation](https://legislature.vermont.gov/Documents/2018/WorkGroups/House%20General/Highlights/4%20-%20Minimum%20Wage%20%20The%20%E2%80%9CBenefits%20Cliff%E2%80%9D%20Presentation.pdf)
for both users and legislators. To see how each piece is calculated, check out the `info` tab in the table of contents on the left.

# Key functionality
- User-facing tool to estimate their own benefits and how it might change over time. 
- Legislator-facing tool to see how benefits change with different combinations of variables
    - eventually, how these variables compare to actual state-wide census variables 
- Repository of sourced overview of how benefits are calculated, for those who are interested.


# Application Links 
- (Reach UP and 3Squares)[https://dcf.vermont.gov/esd/applicants/mybenefits]
- (Child Care Subsidy)[https://cddfamily.my.vermont.gov/s/] 


# Road Map

## Features 

| Feature | Status |
|-------- | -------| 
| Callouts | Planned |
| User-facing calculator | Partial |
| Legislator-facing calculator | Planned | 

## Monthly Benefits

| Benefit | Status |
|---------|--------|
| [3 Squares](Quarto/info/3squaresvt.qmd) | Complete |
| [Child Care Subsidy](Quarto/info/ccfap.qmd) | Complete |
| [Reach Up](Quarto/info/reachup.qmd) | Complete |
| LIHEAP | Planned |
| Lifeline | Planned |
| VT Premium subsidy | Planned |
| Cost sharing VTHC | Planned |
| Medicaid | Complete |

## Tax / Annual

| Benefit | Status |
|---------|--------|
| [Fed. EITC](Quarto/info/Taxes.qmd) | Complete |
| [VT EITC](Quarto/info/Taxes.qmd) | Complete |
| Fed child tax credits | Complete |
| Fed child/dependent care | Planned |
| VT child/dependent care | Planned |
| Fed. Premium subsidy (ACA) | Planned |
| Renter's Rebate | Planned |

## Base

| Benefit | Status |
|---------|--------|
| [After-Tax Income](Quarto/info/Taxes.qmd) | Complete |
| [VT Income Tax](Quarto/info/Taxes.qmd) | Complete |

